### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by lishine** [crsandeep/simple-react-full-stack#18]
Hi,

First thanks for this boilerplate! It got me started with the react-full-stack.

Corrections for the Webpack config, in order client roots to be handled in the client:
output: { publicPath: '/' }
devServer: { historyApiFallback: true }

Also, I can contribute my prettier+eslint config

Also, this modification in the package:

        "client": "webpack-dev-server --hot  --color --progress --mode development -d",
        "server": "nodemon -r esm --watch src/server --inspect src/server/index.js",
        "dev": "concurrently --kill-others \"npm run server\" \"npm run client\"" 

esm enables es6 imports in node

Thanks again

**Comment by lishine** [comment]
In order to deploy to Heroku, need to do this:

const PORT = process.env.PORT || 8080
app.listen(PORT, () => console.log('Listening on port 8080!'))

**Comment by crsandeep** [comment]
@lishine Good catch. Would be awesome if you could send a PR with these changes when you have some free time

**Comment by malas** [comment]
@lishine could you explain a little bit more the additions you made to the configs?

for example `nodemon -r` i can not even find documentation on this option

**Comment by lishine** [comment]
Look for esm package.You can write in node es6 but to us import . This enables us to use import instead of require. -r just runs it, i gess.
My webpack is a function  of mode that I set with the command line. The other flags just help with some info.
Kill others. If one process exits then exit.
Take the port from the environment.
Anything else i can help?

**Comment by malas** [comment]
thanks for such a quick response! 
i have only started to refactor my project into this structure so more questions are yet to come.

**Comment by nikodunk** [comment]
> In order to deploy to Heroku, need to do this:
> 
> const PORT = process.env.PORT || 8080
> app.listen(PORT, () => console.log('Listening on port 8080!'))

Thanks for this! In order to deploy on Heroku, I needed to addionally do:

	heroku config:set NPM_CONFIG_PRODUCTION=false

**Comment by sierra-kilo** [comment]
I'm having an issue with async / await.  With your recent changes, is it supposed to support async / await with no other requirements on my end before writing an async function of do I need to do something else?   

`
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Unexpected token, expected "(" 
`

**Comment by lishine** [comment]
Async await works with the new versions of node.

**Comment by ernestpascual** [comment]
> @lishine Good catch. Would be awesome if you could send a PR with these changes when you have some free time

i actually did just now!

**Comment by ernestpascual** [comment]
> > In order to deploy to Heroku, need to do this:
> > const PORT = process.env.PORT || 8080
> > app.listen(PORT, () => console.log('Listening on port 8080!'))
> 
> Thanks for this! In order to deploy on Heroku, I needed to addionally do:
> 
> ```
> heroku config:set NPM_CONFIG_PRODUCTION=false
> ```

You can also put
```
scripts": {
...
"heroku-prebuild": "npm install --dev",
...
}
```

in your package.json so heroku can install those dependencies
