### ISSUE TITLE
Proxy returning express response not rendered react from json response

### ISSUE THREAD

**Issue by andrew-linck** [crsandeep/simple-react-full-stack#25]
When I make a request. It proxies it, and returns the json that my express returns. But I have it set up so that the react app should get the request and render components based on that request. It worked with my other dev environment. Just not with this proxy
https://github.com/andrew-linck/TourneyStack

**Comment by crsandeep** [comment]
@andrew-linck in your application code, server starts on port 9000 https://github.com/andrew-linck/TourneyStack/blob/master/server/index.js#L6 but the webpack dev server is forwarding /api requests to port 8080 https://github.com/andrew-linck/TourneyStack/blob/master/webpack.config.js#L36. These 2 should match.
