### ISSUE TITLE
Just installed on my vps and dev mode doesnt work

### ISSUE THREAD

**Issue by TheJustExper** [crsandeep/simple-react-full-stack#34]
When i go to port 3000 the page comes up with 
This site can’t be reached X refused to connect.
I have changed none of the webpack code.

**Comment by psybit** [comment]
What VPS service are you using?
Did you open the relevant ports?
If you are using _nginx_ you can redirect connections from port 80 to 3000 through the config file so you don't have to specify the port in the browser's address field.

**Comment by crsandeep** [comment]
closing since there was no response to the above question
