### ISSUE TITLE
Client can access all app files

### ISSUE THREAD

**Issue by kevincastejon** [crsandeep/simple-react-full-stack#38]
Hi thanks for this boilerplate,
I like the structure but I noticed that I can access all files through browser (for example src/server/myPasswords.json is accessible).
How can I avoid that and make the "public" folder the only one to actually be public ?

**Comment by crsandeep** [comment]
@lePioo this should happen only in the dev mode correct? When you deploy it in production, ideally you should not be seeing it. Please let me know if in case this happens in production mode

**Comment by kevincastejon** [comment]
You're right, I just added
`app.use("/public",express.static("public"))`
to make the public folder accessible through browser in production mode
Thanks a lot !
