### ISSUE TITLE
ES6 support for server-side

### ISSUE THREAD

**Issue by kevincastejon** [crsandeep/simple-react-full-stack#56]
Hello, thanks again for this great boilerplate,
how would it be possible to allow ES6 for server-side code ?
I can't figure out how to configure babel to achieve this...

**Comment by empz** [comment]
Node supports 99% of ES2015 since a few LTS versions back. No need for babel.

**Comment by kevincastejon** [comment]
99% is not 100%.. Unfortunately the import and export keywords are still not supported by vanilla nodejs and it's quite annoying to rewrite some code that was written for babelified browser when using it on node environement...
