### ISSUE TITLE
Creating a build, but the API endpoints returns 404 error. 

### ISSUE THREAD

**Issue by praxiz** [crsandeep/simple-react-full-stack#76]
Running 'npm run dev' opens the client and server perfectly fine, but a 'npm run build', with the current webpack configuration, creates a problem. When I upload the files to a webserver, the fetch call to /api/getUsername returns a 404 Not found error. 

Any suggestions as to how to fix this would be greatly appreciated. :)

**Comment by aram0112** [comment]
@praxiz Would you be able to guide me as to how you were able to fix this issue?
