### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by ghost** [crsandeep/simple-react-full-stack#9]
Hi.
Great project, helped me alot.
I have issues with displaying images on front end, my paths for images are something like                             `<a href="/"><img src="/images/logo-3.png" </a>` But always getting error 404 even though they exist. I added the images folder to the public folder.

**Comment by ghost** [comment]
Well, after creating for production use and manually re-creating the images folder in the dist folder worked.

**Comment by crsandeep** [comment]
@mikk-io I looked into webpack configuration and I had not added required loaders to support image. Now I have updated to webpack config and also the example code to load an image.
